// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: test_7_inch_v2

#ifndef _TEST_7_INCH_V2_UI_H
#define _TEST_7_INCH_V2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Label2;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Label3;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_aeionmono144numbers);
LV_FONT_DECLARE( ui_font_aeionmono16);
LV_FONT_DECLARE( ui_font_aeionmono42);
LV_FONT_DECLARE( ui_font_aeionmono48);
LV_FONT_DECLARE( ui_font_alma16);
LV_FONT_DECLARE( ui_font_alma18);
LV_FONT_DECLARE( ui_font_digital100);
LV_FONT_DECLARE( ui_font_digital144);
LV_FONT_DECLARE( ui_font_digital164);
LV_FONT_DECLARE( ui_font_digital30);
LV_FONT_DECLARE( ui_font_digital40);
LV_FONT_DECLARE( ui_font_monofonto100numbers);
LV_FONT_DECLARE( ui_font_monofonto70numbers);
LV_FONT_DECLARE( ui_font_roboto36);
LV_FONT_DECLARE( ui_font_robotonumbers100);
LV_FONT_DECLARE( ui_font_robotonumbers124);
LV_FONT_DECLARE( ui_font_robotonumbers144);
LV_FONT_DECLARE( ui_font_robotonumbers24);
LV_FONT_DECLARE( ui_font_robotonumbers36);
LV_FONT_DECLARE( ui_font_robotonumbers48);
LV_FONT_DECLARE( ui_font_robotonumbers72);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
